-- Script de inicialización para la base de datos de reserva de turnos
-- Este script se ejecuta automáticamente cuando se crea el contenedor

-- Crear un usuario específico para la aplicación (opcional)
-- CREATE USER reserva_user IDENTIFIED BY "ReservaPass123";
-- GRANT CONNECT, RESOURCE TO reserva_user;
-- GRANT UNLIMITED TABLESPACE TO reserva_user;

-- Ejemplo de tabla inicial (se puede crear automáticamente con Hibernate)
-- CREATE TABLE IF NOT EXISTS reservas (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     fecha_hora TIMESTAMP NOT NULL,
--     cliente_nombre VARCHAR2(100) NOT NULL,
--     servicio VARCHAR2(100) NOT NULL,
--     estado VARCHAR2(20) DEFAULT 'PENDIENTE',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Insertar datos de prueba (opcional)
-- INSERT INTO reservas (fecha_hora, cliente_nombre, servicio) VALUES 
--     (TIMESTAMP '2024-01-15 10:00:00', 'Juan Pérez', 'Consulta General'),
--     (TIMESTAMP '2024-01-15 14:30:00', 'María González', 'Revisión Médica');

-- Commit de los cambios
COMMIT;
